FROM cgrlab/typeseqhpv:base_190221

WORKDIR /mnt

RUN Rscript -e 'devtools::install_github("cgrlab/TypeSeqHPV", ref="master", force=TRUE)'

RUN cd / && git clone --single-branch --branch master https://github.com/cgrlab/TypeSeqHPV.git


